=begin
#Tango Card RaaS API

#<p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>. <input type=\"hidden\" id=\"platformNameHolder\" value=\"QAPlatform2\" /><input type=\"hidden\" id=\"platformKeyHolder\" value=\"apYPfT6HNONpDRUj3CLGWYt7gvIHONpDRUYPfT6Hj\" /></p>

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::4CatalogsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe '4CatalogsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::4CatalogsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of 4CatalogsApi' do
    it 'should create an instance of 4CatalogsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::4CatalogsApi)
    end
  end

  # unit tests for get_catalog
  # Get all items in the Platform&#39;s Catalog.
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :verbose Verbose payload
  # @return [CatalogViewVerbose]
  describe 'get_catalog test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
