=begin
#Tango Card RaaS API

#<p>Welcome to the RaaS&reg; API – with this RESTful API you can integrate a global reward or incentive program into your app or platform.<br /><br /> This console works in our Sandbox environment. To receive your own credentials or to ask questions, please contact us <a href=\"mailto:devsupport@tangocard.com\">devsupport@tangocard.com</a>. <input type=\"hidden\" id=\"platformNameHolder\" value=\"QAPlatform2\" /><input type=\"hidden\" id=\"platformKeyHolder\" value=\"apYPfT6HNONpDRUj3CLGWYt7gvIHONpDRUYPfT6Hj\" /></p>

OpenAPI spec version: 2

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/account_view'
require 'swagger_client/models/account_view_summary'
require 'swagger_client/models/billing_address_criteria'
require 'swagger_client/models/brand_view_with_items_verbose'
require 'swagger_client/models/catalog_view'
require 'swagger_client/models/catalog_view_verbose'
require 'swagger_client/models/create_account_criteria'
require 'swagger_client/models/create_credit_card_criteria'
require 'swagger_client/models/create_credit_card_deposit_criteria'
require 'swagger_client/models/create_credit_card_unregister_criteria'
require 'swagger_client/models/create_customer_criteria'
require 'swagger_client/models/create_order_criteria'
require 'swagger_client/models/credential_view'
require 'swagger_client/models/credit_card_criteria'
require 'swagger_client/models/credit_card_deposit_view'
require 'swagger_client/models/credit_card_unregister_view'
require 'swagger_client/models/credit_card_view'
require 'swagger_client/models/customer_view'
require 'swagger_client/models/customer_view_new'
require 'swagger_client/models/customer_view_summary'
require 'swagger_client/models/item_view_verbose'
require 'swagger_client/models/money_view'
require 'swagger_client/models/order_list_item_view'
require 'swagger_client/models/order_list_view'
require 'swagger_client/models/order_reward_view'
require 'swagger_client/models/order_view'
require 'swagger_client/models/order_view_summary'
require 'swagger_client/models/order_view_verbose'
require 'swagger_client/models/page_view'
require 'swagger_client/models/recipient_info_criteria'
require 'swagger_client/models/recipient_info_view'
require 'swagger_client/models/resend_view'
require 'swagger_client/models/sender_info_criteria'
require 'swagger_client/models/sender_info_view'

# APIs
require 'swagger_client/api/customers_api'
require 'swagger_client/api/accounts_api'
require 'swagger_client/api/fund_api'
require 'swagger_client/api/catalogs_api'
require 'swagger_client/api/orders_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
